name: Unit tests

on:
  push:
  pull_request:

jobs:
  tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-module:
          - tests.test_security
          - tests.test_notification

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests (${{ matrix.test-module }})
        run: python -m unittest ${{ matrix.test-module }} -v
